#-----------------------------------------------------------------------

# Use the GNU C/C++ compiler:
CC = gcc
CPP = g++

# COMPILER OPTIONS:

CFLAGS = -g -Wall

#OBJECT FILES
OBJS = dsh.c


dsh: dsh.c run.c
	${CC} dsh.c -o dsh $(CFLAGS)

#-----------------------------------------------------------------------
